// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("pchome.html", "Untitled Page", "PSArchive.ga  PSArchive.ga  Keeping your consoles alive!  All roms are obtained from external sources  PSArchive.ga  PSArchive.ga  PSArchive for the PSP v1.0 Released!  Visit http //psarchive.ga/downloads to get started  PSArchiveStore  PSArchive for the PS3 v2.3.0 Released!  Visit http //psarchive.ga/ps3 to get started  Scan with CashApp to Donate!  Interactive PSP Preview   ", "");
   this[database_length++] = new SearchPage("pcgui.html", "Untitled Page", "PSArchive.ga  PSArchive.ga  Keeping your consoles alive!  All roms are obtained from external sources  PSArchive.ga  PSArchive.ga   ", "");
   this[database_length++] = new SearchPage("downloads.html", "Untitled Page", "PSArchive.ga  PSArchive.ga  Keeping your consoles alive!  All roms are obtained from external sources  PSArchive.ga  PSArchive.ga  PSArchiveStore  Scan with CashApp to Donate!  Interactive PSP Preview  PSArchive Store for PSP  Download   ", "");
   this[database_length++] = new SearchPage("ps3portal.html", "Untitled Page", "For best user experience, it's recommended to open your Internet Browser Menu and select the following   View   Maximum Size Tools   Display Area   Full Pixel   ", "");
   this[database_length++] = new SearchPage("ps3setup.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("setupguide.html", "Untitled Page", "Next, I'll explain how to install games and apps from the site Open the 'Select System' menu on your game / app of choice, you'll be prompted to save it somewhere Here are the appropriate  locations PS1  dev_hdd0   PSXISO PS2  dev_hdd0   PS2ISO PS3  dev_hdd0   PS3ISO Apps  dev_hdd0   packages  Installation via package manager is required here   The menu also includes pointers as to where the files should be saved   How to download games to your modded PSP through the PSFree PS3 Client   Turn on your PSP system and connect it to your Playstation 3 via a miniUSB cable Your PSP should automatically start 'USB Mode' if you have turned this feature off you may need to Select 'USB Connection' from the Settings menu  Once you have downloaded the applicable files, go back to your XMB and navigate to your package manager Find the 'Install Packages from root of mass storage device' option and there you should see the files that you downloaded, install each of the package files  After completing these actions, you should see a new icon for webman mod on your XMB You should be asked to run this to complete installation Launch this application, your PS3 may reboot after this   Next, we want to make sure that your games will display and run correctly For this, we will install the PSFree Webman Mod Custom CFG Click the link below and save the file to 'dev_hdd0   tmp' after that, return to your XMB and navigate to Webman Games   Webman Setup and select 'Refresh webMAN Games & XMB'  How to prepare your PS3 for use with PSFree NO PC REQUIRED!  Note  Although other versions have been known to work, for the best experience it's recommended to be using 4.89 EVILNAT CFW Please note, not every title is available for HEN straight away  Insert a FAT32 USB stick into your PS3 Click on the applicable links below if you don't already have them and save the files to the root of your USB by hovering over your USB drive when prompted and pressing START on your controller  Find a game listed as compatible with the PSP, open the 'Select System' menu and select PSP In the list of download locations, you should now see your PSP Select this and save the game to the 'ISO' folder of your PSP After the download is complete, the game should now show up in your games list   ", "");
   this[database_length++] = new SearchPage("ps3gui.html", "Untitled Page", "Select  PSArchive.ga Store  Games and apps for your PS3 and PSP!  Exit  psfreeps3c v2.3.0   youdontfooljesus   https //www.reddit.com/r/psfree   ", "");
   this[database_length++] = new SearchPage("ps3sidecar.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("sidecaritems.html", "Untitled Page", "YouTube  Playstation 3   Support PSFree via CashApp! 50% donations go to Archive.org  The Godfather  The Don  Playstation 3   Scarface  The World is Yours  Playstation 2    WWE SmackDown vs Raw  Playstation 3   Grand Theft Auto  Liberty Cit  Playstation 2   PSP   PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW  PS3-CFW/HEN  PS3-CFW   PSP   ", "");
   this[database_length++] = new SearchPage("classicscorner.html", "Untitled Page", "Classics Corner   ", "");
   this[database_length++] = new SearchPage("ps3downloads.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("ps3reddeadrevolver.html", "Red Dead Revolver (PS2 Classics)", "Red Dead Revolver  Playstation 2   Vast, rugged, and lawless As a young man, you were helpless to prevent the slaughter of your family at the hands of bandits Many years later, you live as a bounty hunter bringing criminals to justice, while struggling to unravel the mystery of your past You must find those who murdered your family Then, you will take your revenge   ", "");
   this[database_length++] = new SearchPage("ps3pspthesims2.html", "The Sims 2", "The Sims 2  Playstation 2   PSP   An incredible sequel to the best-selling PC game of all-time! You'll get to direct an entire Sims' lifetime, and try to get them to reach their life goals    ", "");
   this[database_length++] = new SearchPage("ps3gtasanandreas.html", "Grand Theft Auto: San Andreas (PS2 Classics)", "Grand Theft Auto  San Andreas  Playstation 2   Five years ago Carl Johnson escaped from the pressures of life in Los Santos, San Andreas a city tearing itself apart with gang trouble, drugs and corruption Where film stars and millionaires do their best to avoid the dealers and gangbangers  Now, it's the early 90s Carl's got to go home His mother has been murdered, his family has fallen apart and his childhood friends are all heading towards disaster  On his return to the neighborhood, a couple of corrupt cops frame him for homicide CJ is forced on a journey that takes him across the entire state of San Andreas, to save his family and to take control of the streets    ", "");
   this[database_length++] = new SearchPage("ps3pspgtavcs.html", "Grand Theft Auto: Vice City Stories (PS2 Classics)", "Grand Theft Auto  Vice City Stories  Playststion 2   PSP   “Vice City, 1984 Opportunity abounds in a city emerging from the swamps, its growth fueled by a violent power struggle in a lucrative drug trade Construction is everywhere as a shining metropolis rises from foundations of crime and betrayal As a soldier, Vic Vance has always protected his dysfunctional family, his country, himself One bad decision later and that job is about to get much harder Kicked out onto the streets between glamour and gluttony, Vic is faced with a stark choice...build an empire or be crushed.”   ", "");
   this[database_length++] = new SearchPage("ps3thesimsbustinout.html", "The Sims Bustin' Out (PS2 Classics)", "The Sims Bustin' Out  PS3   Malcolm Landgraab is going around the neighborhood, repossessing items in return for unpaid rent The player's objective is to complete each career track, unlock and buy back everyone's possessions, and evict Malcolm from his mansion and move their own Sim in    ", "");
   this[database_length++] = new SearchPage("ps3tombraideranniversary.html", "Tomb Raider Anniversary (PS2 Classics)", "Tomb Raider Anniversary  PS3   In 1945 New Mexico, a bomb explodes, engulfing a town and revealing a strange structure, from which a winged creature flies out In Calcutta 1996, Lara Croft is approached by Larson, who introduces her to Jacqueline Natla Natla reveals she has found the location of one of the three pieces that comprise the Atlantean Scion, a mystical artifact buried in the heart of an ancient city, and she wants Lara to retrieve it for her Lara, sitting back leisurely, leaps from her seat upon hearing this revelation Lara, having searched unsuccessfully for such an artifact with her father in the past, agrees to go    ", "");
   this[database_length++] = new SearchPage("ps3totaloverdose.html", "Tomb Raider Anniversary (PS2 Classics)", "Total Overdose  Playstation 2   The player assumes the unexisting role of Ramiro \"Ram\" Cruz  criminal turned DEA Agent He has been sent into the Mexican border city of Los Toros and its surroundings by his twin brother Tommy, who wants him to find out who killed their father Ernesto Cruz The player will be tasked with infiltrating and taking down the biggest drug cartel in Mexico and battling it out with dope dealers, banditos, corrupt Federales and Mexican Army, loco luchadores, guerillas, and other assorted bad guys Between story missions the player can do optional challenge missions as he or she wishes, exploring Los Toros and gathering bonuses to rack up a high score The Furies will try to stop you during the story of Total Overdose    ", "");
   this[database_length++] = new SearchPage("ps3crashbandicootthewrathofcortex.html", "Red Dead Revolver (PS2 Classics)", "Crash Bandicoot  The Wrath of Cortex  PS3   In a newly-built space station orbiting the Earth, Uka Uka, having called a convention of recurring villains in the series, berates Dr Cortex, Tiny Tiger, Dr N Tropy, Dr N Gin and Dingodile for their recently unimpressive evil productivity, and forces them to come up with a plan to eliminate Crash Bandicoot, their main opponent   ", "");
   this[database_length++] = new SearchPage("ps3gun.html", "Red Dead Revolver (PS2 Classics)", "Gun  PS3   Ned White and his son Colton White venture onto the Morningstar, a steamboat on the Montana River The steamboat is attacked by barbaric men lead by a corrupt preacher, Josiah Reed After Ned tells Colton he really isn't his father, the two become separated and Ned dies Now alone and craving vengeance and answers, Colton sets out to the west where he will join a rebellious group of outlaws to battle Indians, stop a corrupt mayor, kill Josiah Reed and stop an evil Civil War Major named Thomas Magruder who has the answers Colton needs as well as a plot of his own to find the Cross of Coronado- the key to the gateway of the lost golden city  WARNING  Game Bug / Glitch Controller must me turned on before the game boots   ", "");
   this[database_length++] = new SearchPage("ps3guitarheroii.html", "Untitled Page", "Guitar Hero II  Deluxe   Playstation 2   Guitar Hero II is the second game in the Guitar Hero series The PS2 version was released on November 7, 2006 The basic gameplay has been changed a great deal from its predecessor, Guitar Hero    ", "");
   this[database_length++] = new SearchPage("ps3scarface.html", "Untitled Page", "Scarface  The World is Yours  Playstation 2   The game begins with the movie's final scene in 1983  The Bolivian Cartel raiding Tony's Mansion Instead of dying, Tony kills the assassin that killed him in the movie, the Skull Tony then fights his way through his mansion, where several of his henchmen are gunned down and explosions rock around the mansion made by Antonio Tony then fights his way through the underground to his pool to escape to his awaiting car, the Ambassador, but the exit is blown up by a bazooka Tony fights his way around the mansion, witnessing his tiger eat Jose, and is almost killed but the police and S.W.A.T who arrive and wipe out the remaining assassins Tony escapes, barely alive, and a surviving assassin informs Sosa that Tony's empire is destroyed over a phone call    ", "");
   this[database_length++] = new SearchPage("ps3manhunt.html", "Untitled Page", "Manhunt  Playstation 2   The game takes place in the gritty crime-infested Carcer City The story opens with a female journalist reporting on the convict James Earl Cash, a criminal on death row who has supposedly been executed by lethal injection Cash is awoken to the voice of a person coming from an earpiece, revealing that Cash was only sedated Cash puts on the earpiece and the person, who refers to himself as \"The Director\", promises Cash his freedom before the night is over, but only if Cash follows the Director's instructions Released in a dingy neighborhood, Cash is directed to slaughter his way through the streets, populated by a gang calling themselves \"The Hoods\", while the Director, watching through security cameras scattered throughout the city, repeatedly mentions the need to please the audiences, revealing his occupation as a snuff film director However, despite the Director's promise of freedom, Cash is beaten and thrown into the back of a van by a group of mercenaries known as the Cerberus    ", "");
   this[database_length++] = new SearchPage("ps3manhunt2.html", "Untitled Page", "Manhunt 2  Playstation 2   In the year 2001, The Pickman Project dealt with a top-secret weapon experiment which was led by Dr Whyte Everything looked to be going well until the project suddenly had its government funding cut due to its controversial work methods, which meant that ‘The Project’ would be shut down indefinitely Dr Pickman believed he was close to a breakthrough and decided to do one last experiment, however he needed a subject in order to carry out his work Daniel volunteered to becoming one of the many subjects for the experiments    ", "");
   this[database_length++] = new SearchPage("ps3thewarriors.html", "Untitled Page", "The Warriors  Playststion 2   The game follows the plot of the film The Warriors, focusing on a Coney Island street gang - the Warriors Led by Cleon, 90 days prior, the Warriors increased their reputation by confronting a small-time gang the Orphans, getting rid of their enemies the Destroyers, spraying on trains, and made alliances with the Saracens by setting up their rivals the Jones Street Boys, along with a group of corrupt police officers of the NYPD Meanwhile, the Gramercy Riffs leader Cyrus plans a meeting to unite the gangs as one    ", "");
   this[database_length++] = new SearchPage("ps3rockband2.html", "Red Dead Revolver (PS2 Classics)", "Rock Band 2  Playststion 3   Rock Band 2 is the second main title in the Rock Band series and the sequel to Rock Band The game was first released in North America on September 14, 2008 for Xbox 360 and October 19, 2008 for PlayStation 3 before being released on PlayStation 2 and Wii on December 18, 2008 In Europe, the game was initially released with the instrument bundle on October 19, 2008 for Xbox 360 before getting a standalone release on November 21, 2008 It was then released in Europe on March 27, 2009 for PlayStation 3 and PlayStation 2 before being released on Wii on October 9, 2009 It features new songs, a new tour mode, and more character customization options Multiplayer has also gotten an overhaul, featuring massive band play online and expanded tour modes    ", "");
   this[database_length++] = new SearchPage("ps3youtube.html", "Red Dead Revolver (PS2 Classics)", "YouTube  Playstation 3   YouTube is an American online video sharing and social media platform headquartered in San Bruno, California It was launched on February 14, 2005, by Steve Chen, Chad Hurley, and Jawed Karim It is currently owned by Google, and is the second most visited website, after Google Search    ", "");
   this[database_length++] = new SearchPage("ps1vampirehunterd.html", "Red Dead Revolver (PS2 Classics)", "Vampire Hunter D  PS1 Classics   Rocket Racer and Veronica Voltage are traveling through time and space in search of the best racers in the galaxy These racers are Captain Redbeard, King Kahuka, Basil the Bat Lord, Johnny Thunder, Baron von Barron, and Gypsy Moth, all of whom host their own racing circuits In an attempt to become champion, the player takes them and fellow racers on Once all of them are defeated, Rocket Racer is challenged The credits roll when he is defeated in a race    ", "");
   this[database_length++] = new SearchPage("ps3legoracers.html", "Untitled Page", "Lego Racers  Playstation 1   Rocket Racer and Veronica Voltage are traveling through time and space in search of the best racers in the galaxy These racers are Captain Redbeard, King Kahuka, Basil the Bat Lord, Johnny Thunder, Baron von Barron, and Gypsy Moth, all of whom host their own racing circuits In an attempt to become champion, the player takes them and fellow racers on Once all of them are defeated, Rocket Racer is challenged The credits roll when he is defeated in a race     ", "");
   this[database_length++] = new SearchPage("gamenfsmostwanted.html", "Untitled Page", "Need for Speed  Most Wanted  Playstation 2   PSP   The player arrives in Rockport as a newbie to the local street racing scene Soon, the player becomes involved with the Blacklist, a list of the most notorious racers in Rockport, and proceeds to challenge Razor, the number 15 on the Blacklist Due to their engine being sabotaged, the player loses the race, resulting in the loss of their BMW M3 GTR GT to Razor and becoming arrested by an approaching squad of the Rockport Police Department   ", "");
   this[database_length++] = new SearchPage("gamemotogp.html", "Untitled Page", "MotoGP  PSP   MotoGP is a racing game released for the PlayStation Portable based on the 2005 and 2006 MotoGP seasons MotoGP was developed by Namco Bandai Games and was released in 2006 The game received average reviews with most critics focusing towards the graphics and gameplay Contents 1 Gameplay 2 Reception 3 References 4 External links Gameplay   ", "");
   this[database_length++] = new SearchPage("gamegtalcs.html", "Untitled Page", "Grand Theft Auto  Liberty City St  Playstation 2   PSP   There are a million stories in Liberty City This one changes everything Once a trusted wise guy in the Leone crime family, Toni Cipriani was forced into hiding after killing a made man Now he's back and it's time for things to be put right   ", "");
   this[database_length++] = new SearchPage("gamealienscolonialmarines.html", "Untitled Page", "Aliens  Colonial Marines  Playstation 3   During the events of Aliens Carter J Burke manages to send a message to Michael Weyland from Weyland-Yutani confirming the existence of the xenomorph species Weyland sends the advanced research transport spacecraft WYS Legato to LV-426 with a cargo of human colonists kept in cryostasis to be used as hosts to the xenomorphs However, the Legato arrives just after the destruction of Hadley's Hope and the departure of the USS Sulaco After investigating the coordinates of the Alien Derelict the corporates discover the ruins of the craft and harvest several xenomorph eggs and begin experimenting with the colonists They also pinpoint the location of the Sulaco through the network and the Colony's computer logs, sending the Legato to intercept the cruiser Just as the corporates connect their ship with the Sulaco a xenomorph outbreak takes place in the Legato    ", "");
   this[database_length++] = new SearchPage("gamethegodfather.html", "Untitled Page", "The Godfather  The Don's Edition  Playstation 3   The Godfather  The Don's Edition is a version of The Godfather  The Game only available for the PlayStation 3 It includes several differences including all the changes made in The Godfather  Blackhand Edition, as well as exclusive content    ", "");
   this[database_length++] = new SearchPage("gamelegoindiana.html", "Untitled Page", "Lego Indiana Jones  The Original Adventures  Playstation 3   LEGO Indiana Jones  The Original Adventures is a video game that follows a LEGO version of Indiana Jones through the first three movies  Raiders of the Lost Ark, Indiana Jones and the Temple of Doom, and Indiana Jones and the Last Crusade The fourth film, Indiana Jones and the Kingdom of the Crystal Skull, appears in the follow-up, LEGO Indiana Jones 2  The Adventure Continues    ", "");
   this[database_length++] = new SearchPage("gamewwesvr2008.html", "Untitled Page", "WWE SmackDown vs Raw 2008  Playstation 3   Each wrestler now has two fighting style categories, one primary and one secondary Each fighting style has its advantages and disadvantages in each particular match type There are eight styles altogether  high-flyer, hardcore, submission artist, powerhouse, showman, brawler, dirty and technical In addition, creative manager of THQ Cory Ledesma stated early in production that he planned on having numerous wrestler animations redone    ", "");
   this[database_length++] = new SearchPage("gamethesimpsonsgame.html", "Untitled Page", "The Simpsons Game  Playstation 3   The Simpsons Game is a video game which is available for the Wii, Nintendo DS, Xbox 360, PlayStation 3, PlayStation 2, and PlayStation Portable Each version has an exclusive cover art It is a third-person action game featuring an original storyline written by Tim Long, Matt Selman, and Matt Warburton The plot is self-referential in nature, with the Simpson family discovering that they are forced to participate in another Simpsons video game Similar to the show, the game pokes fun at popular culture, other video games, and EA, its developer    ", "");
   this[database_length++] = new SearchPage("ps3guiv2.html", "Untitled Page", "PSArchive.ga Store  Games and apps for your PS3 and PSP!  v3.0   psarchive    Store Top  For best user experience, it's recommended to open your Internet Browser Menu and select the following   View   Maximum Size Tools   Display Area   Full Pixel  Donate via CashApp  Classics Corner  WWE SmackDown vs Raw  Playstation 3   Grand Theft Auto  Liberty Cit  Playstation 2   PSP   PS3-CFW/HEN  PS3-CFW   PSP  Scarface  The World is Yours  Playstation 2    PS3-CFW  User  Select  Exit   ", "");
   this[database_length++] = new SearchPage("alldownloads.html", "Untitled Page", "Featured Downloads  Playstation Portable  All Downloads   ", "");
   this[database_length++] = new SearchPage("ps3list.html", "Untitled Page", "Total Overdose  Playstation 2   The Sims Bustin' Out  Playstation 2   The Sims 2  Playstation 2   PSP    Grand Theft Auto  Vice  Playststion 2   PSP    Red Dead Revolver  Playstation 2    Grand Theft Auto  San  Playstation 2   Crash Bandicoot  The  Playstation 2   Guitar Hero II  Deluxe   Playstation 2   Scarface  The World is  Playstation 2   Manhunt  PS2   Manhunt 2  PS2   Manhunt  Playstation 2   Manhunt 2  Playstation 2   The Warriors  PS3   Rock Band 2  Playstation 3   The Warriors  Playstation 2   PS3-CFW  PS3-CFW  PS3-CFW  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN   PSP  PS3-HEN   PSP  PS3-HEN  PS3-HEN  Lego Racers  Playstation 1   PS3-CFW/HEN  Need for Speed  Most  Playstation 2   PSP   PS3-CFW   PSP  MotoGP  PSP   PSP  Grand Theft Auto  Libe  Playstation 2   PSP   PS3-CFW   PSP  Aliens  Colonial Marines  Playstation 3   LEGO Indiana Jones  T  Playstation 3   PS3-CFW/HEN  The Godfather  The Do  Playstation 3   PS3-CFW/HEN  COMING SOON!  The Simpsons Game  Playstation 3   PSP   PS3-CFW/HEN   PSP  WWE SmackDown vs  Playstation 3   PS3-CFW/HEN  YouTube  Playstation 3   PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW   PSP   ", "");
   this[database_length++] = new SearchPage("playstationportable.html", "Untitled Page", "Featured Downloads  Playstation Portable  All Downloads   ", "");
   this[database_length++] = new SearchPage("pspportal.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  Is your favourite game not here?  Submit a request to reddit.com/ r/psfree   ", "");
   this[database_length++] = new SearchPage("pspsidecar.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("pspsidecaritems.html", "Untitled Page", "Grand Theft Au  PSP   MotoGP  PSP   Grand Theft Au  PSP    ", "");
   this[database_length++] = new SearchPage("pspgui.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus   ", "");
   this[database_length++] = new SearchPage("pspdownloads.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  Playstation Portable   ", "");
   this[database_length++] = new SearchPage("psplist.html", "Untitled Page", "Grand Theft Auto  Vi  PSP   MotoGP  PSP   Grand Theft Auto  Li  PSP   Need for Speed  Most  PSP   The Sims 2  PSP    ", "");
   this[database_length++] = new SearchPage("pspgtavcs.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  Grand Theft Auto  Vice City Stories PSP  Vice City, 1984 Opportunity abounds in a city emerging from the swamps, its growth fueled by a violent power struggle in a lucrative drug trade Construction is everywhere as a shining metropolis rises from foundations of crime and betrayal As a soldier, Vic Vance has always protected his dysfunctional family, his country, himself One bad decision later and that job is about to get much harder   ", "");
   this[database_length++] = new SearchPage("pspgtalcs.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  Grand Theft Auto  Liberty City Stories PSP  There are a million stories in Liberty City This one changes everything Once a trusted wise guy in the Leone crime family, Toni Cipriani was forced into hiding after killing a made man Now he's back and it's time for things to be put right   ", "");
   this[database_length++] = new SearchPage("pspmotogp.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  MotoGP PSP  MotoGP is a racing game released for the PlayStation Portable based on the 2005 and 2006 MotoGP seasons MotoGP was developed by Namco Bandai Games and was released in 2006 The game received average reviews with most critics focusing towards the graphics and gameplay Contents 1 Gameplay 2 Reception 3 References 4 External links Gameplay   ", "");
   this[database_length++] = new SearchPage("pspnfsmostwanted.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  Need for Speed  Most Wanted PSP  The player arrives in Rockport as a newbie to the local street racing scene Soon, the player becomes involved with the Blacklist, a list of the most notorious racers in Rockport, and proceeds to challenge Razor, the number 15 on the Blacklist   ", "");
   this[database_length++] = new SearchPage("thesims2.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  The Sims 2 PSP  The Sims 2  PSP  is the first of The Sims series for the PlayStation Portable system It takes place in Strangetown, but unlike the GBA and DS versions, the PSP version is based on the Windows version  the graphics are similar This is the only PSP Sims game that is minigame as well as mission based   ", "");
   this[database_length++] = new SearchPage("setup.html", "Untitled Page", "PSArchiveStore  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus  On a PS3 system already set up to use PSFree or a PC/Mac, connect your PSP to the system with a memory card inserted via a Mini-USB cable Click on the links below and save the files to the 'seplugins' folder of your PSP  If it doesn't exist create it   Once all the files have been downloaded to the PSP, reboot it  You're all done! Pick a category from the above menu and download a game of your choosing Games should be saved to the ISO folder   ", "");
   return this;
}
