// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "PSArchive Home", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION  PSArchive for the PSP v1.0 Released!  Visit http //www.psarchive.tk/downloads to get started  PSArchiveStore  PSArchive Store PS3 3.0 Released!  Visit http //www.psarchive.tk/ps3 to get started  Scan with CashApp to Donate!  Thank You! PSPMav for creating this video    ", "");
   this[database_length++] = new SearchPage("pcgui.html", "Untitled Page", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION   ", "");
   this[database_length++] = new SearchPage("downloads.html", "Untitled Page", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION  PSArchiveStore  Scan with CashApp to Donate!  Interactive PSP Preview  PSArchive Store for PSP  Download  App will display under Internet Radio   PSArchive Store for PS3  App in development!  For now use the Internet Browser to browse www.psarchive.tk/ps3    ", "");
   this[database_length++] = new SearchPage("psp.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Store Top  Donate via CashApp  The Simpsons Game  Playstation 3   PSP   Donate via CashApp  Donate via CashApp  Thank you for visiting the PSArchive Store! We hope you enjoy your stay   ", "");
   this[database_length++] = new SearchPage("pspgui.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive   ", "");
   this[database_length++] = new SearchPage("pspdownloads.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  All Downloads   ", "");
   this[database_length++] = new SearchPage("psplist.html", "Untitled Page", "Crash Bandicoot  The Wrath of Cortex  Playstation 3   Guitar Hero II  Deluxe  Playstation 3   Manhunt  Playstation 3   The Warriors  Playstation 3   PSP   LEGO Indiana Jones  The Original Adventures  Playstation 3   YouTube  Playstation 3   The Godfather  The Don's Edition  Playstation 3   MediEvil  Resurrection  PSP   Ace Combat X  Skies of Deception  PSP   Total Overdose  Playstation 3   The Sims 2  Playstation 3   PSP   Red Dead Revolver  Playstation 3   MotoGP  Playstation 3   PSP   WWE SvR 2008  Playstation 3   PSP   Manhunt 2  Playstation 3   PSP   Rockband 2  Playstation 3   Mega Man  Powered Up  PSP   NickToons Racing  Playstation 3   Super Mario 64 HD  Playstation 3   The Sims  Playstation 2   Available on  PS3  The Sims  Playstation 3   Grand Theft Auto  Vice City Stories  Playstation 2   Available on  PS3   PSP  Grand Theft Auto  Vice City Stories  Playstation 3   PSP   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Grand Theft Auto  San Andreas  Playstation 3   Need for Speed  Most Wanted  Playstation 3   PSP   Grand Theft Auto  Liberty City Stories  Playstation 3   PSP   The Simpsons Game  Playstation 3   PSP   LEGO Racers  Playstation 3   Scarface  The World is Yours  Playstation 3   Mega Man  Maverick Hunter X  PSP   Ace Combat  Joint Assault  PSP    ", "");
   this[database_length++] = new SearchPage("pspgtavcs.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Grand Theft Auto  Vice City Stories PSP  Vice City, 1984 Opportunity abounds in a city emerging from the swamps, its growth fueled by a violent power struggle in a lucrative drug trade Construction is everywhere as a shining metropolis rises from foundations of crime and betrayal As a soldier, Vic Vance has always protected his dysfunctional family, his country, himself One bad decision later and that job is about to get much harder   ", "");
   this[database_length++] = new SearchPage("pspgtalcs.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Grand Theft Auto  Liberty City Stories PSP  There are a million stories in Liberty City This one changes everything Once a trusted wise guy in the Leone crime family, Toni Cipriani was forced into hiding after killing a made man Now he's back and it's time for things to be put right   ", "");
   this[database_length++] = new SearchPage("pspmotogp.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  MotoGP PSP  MotoGP is a racing game released for the PlayStation Portable based on the 2005 and 2006 MotoGP seasons MotoGP was developed by Namco Bandai Games and was released in 2006 The game received average reviews with most critics focusing towards the graphics and gameplay Contents 1 Gameplay 2 Reception 3 References 4 External links Gameplay   ", "");
   this[database_length++] = new SearchPage("pspnfsmostwanted.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Need for Speed  Most Wanted PSP  The player arrives in Rockport as a newbie to the local street racing scene Soon, the player becomes involved with the Blacklist, a list of the most notorious racers in Rockport, and proceeds to challenge Razor, the number 15 on the Blacklist   ", "");
   this[database_length++] = new SearchPage("pspthesims2.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  The Sims 2 PSP  The Sims 2  PSP  is the first of The Sims series for the PlayStation Portable system It takes place in Strangetown, but unlike the GBA and DS versions, the PSP version is based on the Windows version  the graphics are similar This is the only PSP Sims game that is minigame as well as mission based   ", "");
   this[database_length++] = new SearchPage("pspthesimpsonsgame.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  The Simpsons Game PSP  Players are able to control four of the five members of the family, each with their own unique abilities Maggie is, in effect, an extension of Marge, briefly being playable in air ducts and other small spaces   ", "");
   this[database_length++] = new SearchPage("pspmanhunt2.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Manhunt 2 PSP  During a severe thunderstorm, the security systems at the Dixmor Asylum for the Criminally Insane momentarily go offline, opening the cell doors throughout the facility, resulting in the populace wandering freely through the corridors Two such inmates are Daniel Lamb and Leo Kasper   ", "");
   this[database_length++] = new SearchPage("pspmegamanmavhuntx.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Mega Man Maverick Hunter X PSP  A brand-new graphical art style featuring 3D graphics Many characters and items have been redesigned to a more modern aesthetic reminiscent of Mega Man X8, which released in the same year as this title  e.g Light Capsule designs, Life Energy and Weapon Energy designs, Ride Armor designs  Notably, the eight Maverick bosses have undergone heavy redesigns   ", "");
   this[database_length++] = new SearchPage("pspmegamanpoweredup.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Mega Man Powered Up PSP  The game features a new super deformed art style in addition to two new Robot Masters, Time Man and Oil Man Also, like in Mega Man 7, Mega Man 8, Mega Man & Bass, and the Mega Man X series, there is a new introductory level that comes before the main level selection screen, complete with a new boss at the end   ", "");
   this[database_length++] = new SearchPage("pspmedievilresurrection.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  MediEvil  Resurrection PSP  Gameplay is similar to that of the original game Dan can utilise a variety of weapons, including melee weapons such as swords and axes and ranged weapons like throwing daggers and crossbows   ", "");
   this[database_length++] = new SearchPage("pspgodseaterburst.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Gods Eater Burst PSP  The Burst arc of the game, the story revolves around the 1st Unit's search for Lindow Amamiya which results in the arrival of Ren and a new Aragami, the Corrosive Hannibal   ", "");
   this[database_length++] = new SearchPage("pspacecombatxskies.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Ace Combat X  Skies of D PSP  The Federal Republic of Aurelia is a peaceful and wealthy nation located on the southern edge of the South Osean continent Its mild climate and vast underground resources have kept Aurelia out of war and conflicts for many decades   ", "");
   this[database_length++] = new SearchPage("pspacecombatjointassault.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  Ace Combat  Joint Assault  The plot of Joint Assault takes place in late 2010 and early 2011, 4  during the Great Recession The story opens with the private military company Martinez Security participating in a military exercise with the United States Navy Seventh Fleet and Japan Self-Defense Forces in the Pacific Ocean   ", "");
   this[database_length++] = new SearchPage("setup.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  v3.0   PSArchive  On a PS3 system already set up to use PSFree or a PC/Mac, connect your PSP to the system with a memory card inserted via a Mini-USB cable Click on the links below and save the files to the 'seplugins' folder of your PSP  If it doesn't exist create it   Once all the files have been downloaded to the PSP, reboot it  You're all done! Pick a category from the above menu and download a game of your choosing Games should be saved to the ISO folder   ", "");
   this[database_length++] = new SearchPage("ps3.html", "", "PSArchive.tk Store  Games and apps for your PS3 and PSP!  Store Top  For best user experience, it's recommended to open your Internet Browser Menu and select the following   View   Maximum Size Tools   Display Area   Full Pixel  User  Select  Exit  v3.1.0   PSArchive  Donate via CashApp   ", "");
   this[database_length++] = new SearchPage("alldownloads.html", "Untitled Page", "Featured Downloads  All Downloads   ", "");
   this[database_length++] = new SearchPage("ps3list.html", "Untitled Page", "The Sims  Playstation 2   Available on  PS3  Total Overdose  Playstation 3   Crash Bandicoot  The Wrath of Cortex  Playstation 3   The Sims  Playstation 3   Grand Theft Auto  Vice City Stories  Playstation 2   Available on  PS3   PSP  The Sims 2  Playstation 3   PSP   Guitar Hero II  Deluxe  Playstation 3   Grand Theft Auto  Vice City Stories  Playstation 3   PSP   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Red Dead Revolver  Playstation 3   Manhunt  Playstation 3   Grand Theft Auto  San Andreas  Playstation 3   Need for Speed  Most Wanted  Playstation 3   PSP   MotoGP  Playstation 3   PSP   The Warriors  Playstation 3   PSP   Grand Theft Auto  Liberty City Stories  Playstation 3   PSP   LEGO Indiana Jones  The Original Adventures  Playstation 3   The Simpsons Game  Playstation 3   PSP   WWE SvR 2008  Playstation 3   PSP   YouTube  Playstation 3   LEGO Racers  Playstation 3   Manhunt 2  Playstation 3   PSP   The Godfather  The Don's Edition  Playstation 3   Scarface  The World is Yours  Playstation 3   Rockband 2  Playstation 3   MediEvil  Resurrection  PSP   Mega Man  Maverick Hunter X  PSP   Mega Man  Powered Up  PSP   Ace Combat X  Skies of Deception  PSP   Ace Combat  Joint Assault  PSP   NickToons Racing  Playstation 3   Super Mario 64 HD  Playstation 3    ", "");
   this[database_length++] = new SearchPage("featured.html", "Untitled Page", "Featured Downloads  All Downloads   ", "");
   this[database_length++] = new SearchPage("featuredlist.html", "Untitled Page", "YouTube  Playstation 3   Manhunt 2  Playstation 3   PSP    ", "");
   this[database_length++] = new SearchPage("classicscorner.html", "Untitled Page", "Classics Corner  MediEvil  Resurrection  PSP   The Simpsons Game  Playstation 3   PSP   Grand Theft Auto  San Andreas  Playstation 2   Available on  PS3  Grand Theft Auto  San Andreas  Playstation 3    ", "");
   return this;
}
