// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "PSArchive Home", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION  PSArchive for the PSP v1.0 Released!  Visit http //www.psarchive.tk/downloads to get started  PSArchiveStore  PSArchive Store PS3 3.0 Released!  Visit http //www.psarchive.tk/ps3 to get started  Scan with CashApp to Donate!  Thank You! PSPMav for creating this video    ", "");
   this[database_length++] = new SearchPage("pcgui.html", "Untitled Page", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION   ", "");
   this[database_length++] = new SearchPage("downloads.html", "Untitled Page", "www.psarchive.tk  www.psarchive.tk  Keeping your consoles alive!  www.psarchive.tk  www.psarchive.tk  WEBSITE UNDER CONSTRUCTION  PSArchiveStore  Scan with CashApp to Donate!  Interactive PSP Preview  PSArchive Store for PSP  Download  App will display under Internet Radio   PSArchive Store for PS3  App in development!  For now use the Internet Browser to browse www.psarchive.tk/ps3    ", "");
   this[database_length++] = new SearchPage("psp.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0   ", "");
   this[database_length++] = new SearchPage("pspsidecar.html", "Untitled Page", " ", "");
   this[database_length++] = new SearchPage("pspsidecaritems.html", "Untitled Page", "Grand Theft Au  PSP   MediEvil  Resur  PSP   Ace Combat X    PSP   MotoGP  PSP   The Sims 2  PSP    ", "");
   this[database_length++] = new SearchPage("pspgui.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0   ", "");
   this[database_length++] = new SearchPage("pspdownloads.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Playstation Portable   ", "");
   this[database_length++] = new SearchPage("psplist.html", "Untitled Page", "Grand Theft Auto  Vi  PSP   MotoGP  PSP   Grand Theft Auto  Li  PSP   Need for Speed  Most  PSP   The Sims 2  PSP   The Simpsons Game  PSP   Manhunt 2  PSP   Mega Man Maverick  PSP   Mega Man Powered Up  PSP   MediEvil  Resurrection  PSP   Ace Combat  Joint A  PSP   Ace Combat X  Skie  PSP    ", "");
   this[database_length++] = new SearchPage("pspgtavcs.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Grand Theft Auto  Vice City Stories PSP  Vice City, 1984 Opportunity abounds in a city emerging from the swamps, its growth fueled by a violent power struggle in a lucrative drug trade Construction is everywhere as a shining metropolis rises from foundations of crime and betrayal As a soldier, Vic Vance has always protected his dysfunctional family, his country, himself One bad decision later and that job is about to get much harder   ", "");
   this[database_length++] = new SearchPage("pspgtalcs.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Grand Theft Auto  Liberty City Stories PSP  There are a million stories in Liberty City This one changes everything Once a trusted wise guy in the Leone crime family, Toni Cipriani was forced into hiding after killing a made man Now he's back and it's time for things to be put right   ", "");
   this[database_length++] = new SearchPage("pspmotogp.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  MotoGP PSP  MotoGP is a racing game released for the PlayStation Portable based on the 2005 and 2006 MotoGP seasons MotoGP was developed by Namco Bandai Games and was released in 2006 The game received average reviews with most critics focusing towards the graphics and gameplay Contents 1 Gameplay 2 Reception 3 References 4 External links Gameplay   ", "");
   this[database_length++] = new SearchPage("pspnfsmostwanted.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Need for Speed  Most Wanted PSP  The player arrives in Rockport as a newbie to the local street racing scene Soon, the player becomes involved with the Blacklist, a list of the most notorious racers in Rockport, and proceeds to challenge Razor, the number 15 on the Blacklist   ", "");
   this[database_length++] = new SearchPage("pspthesims2.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  The Sims 2 PSP  The Sims 2  PSP  is the first of The Sims series for the PlayStation Portable system It takes place in Strangetown, but unlike the GBA and DS versions, the PSP version is based on the Windows version  the graphics are similar This is the only PSP Sims game that is minigame as well as mission based   ", "");
   this[database_length++] = new SearchPage("pspthesimpsonsgame.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  The Simpsons Game PSP  Players are able to control four of the five members of the family, each with their own unique abilities Maggie is, in effect, an extension of Marge, briefly being playable in air ducts and other small spaces   ", "");
   this[database_length++] = new SearchPage("pspmanhunt2.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Manhunt 2 PSP  During a severe thunderstorm, the security systems at the Dixmor Asylum for the Criminally Insane momentarily go offline, opening the cell doors throughout the facility, resulting in the populace wandering freely through the corridors Two such inmates are Daniel Lamb and Leo Kasper   ", "");
   this[database_length++] = new SearchPage("pspmegamanmavhuntx.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Mega Man Maverick Hunter X PSP  A brand-new graphical art style featuring 3D graphics Many characters and items have been redesigned to a more modern aesthetic reminiscent of Mega Man X8, which released in the same year as this title  e.g Light Capsule designs, Life Energy and Weapon Energy designs, Ride Armor designs  Notably, the eight Maverick bosses have undergone heavy redesigns   ", "");
   this[database_length++] = new SearchPage("pspmegamanpoweredup.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Mega Man Powered Up PSP  The game features a new super deformed art style in addition to two new Robot Masters, Time Man and Oil Man Also, like in Mega Man 7, Mega Man 8, Mega Man & Bass, and the Mega Man X series, there is a new introductory level that comes before the main level selection screen, complete with a new boss at the end   ", "");
   this[database_length++] = new SearchPage("pspmedievilresurrection.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  MediEvil  Resurrection PSP  Gameplay is similar to that of the original game Dan can utilise a variety of weapons, including melee weapons such as swords and axes and ranged weapons like throwing daggers and crossbows   ", "");
   this[database_length++] = new SearchPage("pspgodseaterburst.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Gods Eater Burst PSP  The Burst arc of the game, the story revolves around the 1st Unit's search for Lindow Amamiya which results in the arrival of Ren and a new Aragami, the Corrosive Hannibal   ", "");
   this[database_length++] = new SearchPage("pspacecombatxskies.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Ace Combat X  Skies of D PSP  The Federal Republic of Aurelia is a peaceful and wealthy nation located on the southern edge of the South Osean continent Its mild climate and vast underground resources have kept Aurelia out of war and conflicts for many decades   ", "");
   this[database_length++] = new SearchPage("pspacecombatjointassault.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  Ace Combat  Joint Assault  The plot of Joint Assault takes place in late 2010 and early 2011, 4  during the Great Recession The story opens with the private military company Martinez Security participating in a military exercise with the United States Navy Seventh Fleet and Japan Self-Defense Forces in the Pacific Ocean   ", "");
   this[database_length++] = new SearchPage("setup.html", "Untitled Page", "PSArchive.tkStore  Navigate  Select  psarchive2.0  On a PS3 system already set up to use PSFree or a PC/Mac, connect your PSP to the system with a memory card inserted via a Mini-USB cable Click on the links below and save the files to the 'seplugins' folder of your PSP  If it doesn't exist create it   Once all the files have been downloaded to the PSP, reboot it  You're all done! Pick a category from the above menu and download a game of your choosing Games should be saved to the ISO folder   ", "");
   this[database_length++] = new SearchPage("page1.html", "Untitled Page", "PSArchiveRadio  Navigate  Select  psfreepspc v1.0.0   youdontfooljesus   ", "");
   this[database_length++] = new SearchPage("ps3.html", "", "PSArchive.tk Store  Games and apps for your PS3 and PSP!  Store Top  For best user experience, it's recommended to open your Internet Browser Menu and select the following   View   Maximum Size Tools   Display Area   Full Pixel  Donate via CashApp  User  Select  Exit   ", "");
   this[database_length++] = new SearchPage("alldownloads.html", "Untitled Page", "  Featured Downloads  Playstation Portable  All Downloads    Featured Downloads  Playstation Portable  All Downloads   ", "");
   this[database_length++] = new SearchPage("ps3list.html", "Untitled Page", "Total Overdose    Playstation 2   The Sims Bustin' Out    Playstation 2   The Sims 2    Playstation 2   PSP      Grand Theft Auto  Vice    Playststion 2   PSP      Red Dead Revolver    Playstation 2      Grand Theft Auto  San    Playstation 2   Crash Bandicoot  The    Playstation 2   Guitar Hero II  Deluxe     Playstation 2   Scarface  The World is    Playstation 2   Manhunt    PS2   Manhunt 2    PS2   Manhunt    Playstation 2   Manhunt 2    Playstation 2   The Warriors    PS3   Rock Band 2    Playstation 3   The Warriors    Playstation 2   PS3-CFW  PS3-CFW  PS3-CFW  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN   PSP  PS3-HEN   PSP  PS3-HEN  PS3-HEN  Lego Racers    Playstation 1   PS3-CFW/HEN  Need for Speed  Most    Playstation 2   PSP   PS3-CFW   PSP  MotoGP    PSP   PSP  Grand Theft Auto  Libe    Playstation 2   PSP   PS3-CFW   PSP  Aliens  Colonial Marines    Playstation 3   LEGO Indiana Jones  T    Playstation 3   PS3-CFW/HEN  The Godfather  The Do    Playstation 3   PS3-CFW/HEN  The Simpsons Game    Playstation 3   PSP   PS3-CFW/HEN   PSP  WWE SmackDown vs    Playstation 3   PS3-CFW/HEN  YouTube    Playstation 3   PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW/HEN  PS3-CFW   PSP  MediEvil  Resurrection    PSP   PSP  Mega Man Maverick H    PSP   PSP  Mega Man Powered Up    PSP   PSP  Ace Combat X  Skies    PSP   PSP  Ace Combat  Joint Ass    PSP   PSP  Nicktoons Racing    Playstation 1   PS3-CFW   ", "");
   this[database_length++] = new SearchPage("classicscorner.html", "Untitled Page", "Classics Corner  WWE SmackDown vs Raw    Playstation 3   Grand Theft Auto  Liberty Cit    Playstation 2   PSP   PS3-CFW/HEN  PS3-CFW   PSP  Scarface  The World is Yours    Playstation 2      PS3-CFW   ", "");
   return this;
}
